### ISSUE TITLE
can't change laungage

### ISSUE THREAD

**Issue by duch3201** [duch3201/LightFile#15]
```
Traceback (most recent call last):
  File "Y:\LightFile\config.py", line 35, in <module>
    if(exists == False):
NameError: name 'exists' is not defined
```
after adding this:
![image](https://user-images.githubusercontent.com/56601374/106902177-cd774380-66f8-11eb-9b3e-105938a37690.png)
to the config file

**Comment by Mathewnd** [comment]
You dont seem to have a variable named exists in the first place

**Comment by duch3201** [comment]
it somehow works now
